import { type NextPage } from "next";
import Login from "./home/login";
import Head from "next/head";
// import Link from "next/link";
// import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";

import bg from "public/pexels-adam-lukac-773958.jpg";

// fonts

import { Montagu_Slab, Overpass_Mono } from "@next/font/google";

const montagu = Montagu_Slab({
  subsets: ["latin"],
  variable: "--font-montagu",
});

const overpass = Overpass_Mono({
  subsets: ["latin"],
  variable: "--font-overpass",
});

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Brewtal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{ backgroundImage: `url(${bg.src})` }}
        className={`flex min-h-screen flex-col items-center justify-center ${montagu.variable} font-sans`}
      >
        <Login hello={hello.data?.greeting} />
      </main>
    </>
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined },
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => signOut() : () => signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
